# Generated by Django 3.2.20 on 2023-07-18 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_hashtag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x0000029DB633F0C8><django.db.models.query_utils.DeferredAttribute object at 0x0000029DB633F088>', max_length=16, unique=True),
        ),
    ]
