# Generated by Django 3.2.20 on 2023-07-18 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_profile_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x00000125EDE9F148><django.db.models.query_utils.DeferredAttribute object at 0x00000125EDE9F108>', max_length=16, unique=True),
        ),
    ]
