# Generated by Django 3.2.20 on 2023-07-18 08:15

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20230718_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x0000027C914610C8><django.db.models.query_utils.DeferredAttribute object at 0x0000027C91461088>', max_length=16, unique=True),
        ),
    ]
