# Generated by Django 3.2.20 on 2023-07-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20230718_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x0000028ADDCCEEC8><django.db.models.query_utils.DeferredAttribute object at 0x0000028ADDCCEE88>', max_length=16, unique=True),
        ),
    ]
