# Generated by Django 3.2.20 on 2023-07-18 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20230718_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x0000020D91630088><django.db.models.query_utils.DeferredAttribute object at 0x0000020D91630188>', max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_accounts',
            field=models.TextField(blank=True, null=True),
        ),
    ]
